name: GitHub Actions Demo
on: [push]
permissions:
  pull-requests: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job ${{ github.run_number }} is now running on a ${{ runner.os }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Produce File"
        run: |
          echo 'This must be comitted' > out.dat
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit data
        run: |
          git add out.dat
          git commit -m "Add results"
      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          gh pr create --title "Update results" --body "This PR adds the latest results file." --head $BRANCH_NAME --base main
      - run: echo "🍏 This job's status is ${{ job.status }}."

